apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      env: production
  replicas: 6
  template:
    metadata:
      name: myapp-nginx
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx